config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  # get '/spotify_auth', to: 'application#spotify_auth'

  get 'comments/index'
  post 'comments/create'
  get 'comments/:comment_id/replies', to: 'replies#index', as: :comments_replies_index
  get 'comments/:comment_id/replies/hide', to: 'replies#hide', as: :comments_replies_hide
  post 'comments/:comment_id/replies', to: 'replies#create', as: :comments_replies_create

  get 'episodes/:id', to: 'episodes#show', as: :episode
  get 'episodes/index'
  get 'episodes/search'

  get 'podcasts/index'
  get 'podcasts/show/:id', to: 'podcasts#show', as: :podcasts_show
  get 'podcasts/search'

  # get '/users/spotify/omniauth_authorize', to: 'users/omniauth_callbacks#spotify', as: :user_spotify_omniauth_authorize
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions',
  # registrations: 'users/registrations'}
  # config/routes.rb
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

# Custom route for Spotify OmniAuth authorization
# get '/users/spotify/omniauth_authorize', to: 'users/omniauth_callbacks#spotify', as: :user_spotify_omniauth_authorize


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/reply.rb
class Reply < ApplicationRecord
  after_create_commit :append_new_reply
  belongs_to :user
  belongs_to :comment

  def append_new_reply
    broadcast_update_to(
      self.comment.episode,
      target:  "comment-#{self.comment_id}-link-to-replies",
      html: "#{ self.comment.replies.count } Reply".pluralize(self.comment.replies.count)
    )
    broadcast_append_to(
      self.comment.episode,
      target:  "#{self.comment.replies_list_id}-list",
      html: ApplicationController.render(
        ReplyComponent.new(reply: self),
        layout: false
      )
    )
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_user!

  def index
    @replies = current_comment.replies.includes(:user)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to episode_url(current_episode) }
    end
  end

  def hide
    @count = current_comment.replies.length
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to episode_url(current_episode) }
    end
  end

  def create
    current_user.replies.create(reply_params)

    respond_to do |format|
      format.html { redirect_to episode(current_episode) }
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          "reply-form",
          partial: '/replies/form',
          locals: {reply: Reply.new,
          comment: current_comment,
          }
        )
      end
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:content, :comment_id)
  end

  def current_episode
    current_comment.episode
  end

  def current_comment
    @current_comment ||= Comment.find_by_id(params[:comment_id])
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<div id= "reply-form" class="mt-6 flex gap-x-3">
  <img src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="h-6 w-6 flex-none rounded-full bg-gray-50">
  <%= form_with model: reply, id: "new_reply_form", url: comments_replies_create_path(comment), method: :post, data: {turbo_frame: "episode"}, class: "relative flex-auto" do |form| %>
    <div class="overflow-hidden rounded-lg pb-12 shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600">
      <%= form.label :reply, "Add your reply", class: "block ml-5 text-sm font-medium leading-6 text-gray-900" %>
      <%= form.hidden_field :comment_id, value: comment.id %>
      <%= form.text_area :content, rows: 4, class: "block w-full resize-none border-0 bg-transparent py-1.5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6", placeholder:"Add your comment..." %>
    </div>
    <%= form.submit 'Post', class: "px-4 py-3 ml-3 font-medium bg-gray-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-gray-400 focus:ring-4 ring-0 focus:ring-gray-100" %>
  <% end %>
</div>

app/views/replies/hide.turbo_stream.erb
<%= turbo_stream.replace "hide-comment-#{@current_comment.id}-link-to-replies" do %>
  <%= link_to "#{pluralize(@count, "Reply")}", comments_replies_index_path(@current_comment), id: "comment-#{@current_comment.id}-link-to-replies", data: { turbo_stream: "comment-#{ @current_comment.id }-replies" }, class: "text-xs text-indigo-600 hover:text-indigo-900" %>
 <% end %>

<%= turbo_stream.update @current_comment.replies_list_id %>

app/views/replies/index.turbo_stream.erb
<%= turbo_stream.replace "comment-#{@current_comment.id}-link-to-replies" do %>
  <%= link_to "Hide", comments_replies_hide_path(@current_comment), id: "hide-comment-#{@current_comment.id}-link-to-replies", data: { turbo_stream: "comment-#{ @current_comment.id }-replies" }, class: "text-xs text-indigo-600 hover:text-indigo-900" %>
<% end %>

<%= turbo_stream.update @current_comment.replies_list_id do %>
  <ul id=<%=  "#{@current_comment.replies_list_id}-list" %> >
    <%= render ReplyComponent.with_collection(@replies) %>
  </ul>
   <%= render 'replies/form', reply: Reply.new, comment: @current_comment %>
<% end %>