config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  # get '/spotify_auth', to: 'application#spotify_auth'

  get 'comments/index'
  post 'comments/create'
  get 'comments/:comment_id/replies', to: 'replies#index', as: :comments_replies_index
  get 'comments/:comment_id/replies/hide', to: 'replies#hide', as: :comments_replies_hide
  post 'comments/:comment_id/replies', to: 'replies#create', as: :comments_replies_create

  get 'episodes/:id', to: 'episodes#show', as: :episode
  get 'episodes/index'
  get 'episodes/search'

  get 'podcasts/index'
  get 'podcasts/show/:id', to: 'podcasts#show', as: :podcasts_show
  get 'podcasts/search'

  # get '/users/spotify/omniauth_authorize', to: 'users/omniauth_callbacks#spotify', as: :user_spotify_omniauth_authorize
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions',
  # registrations: 'users/registrations'}
  # config/routes.rb
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

# Custom route for Spotify OmniAuth authorization
# get '/users/spotify/omniauth_authorize', to: 'users/omniauth_callbacks#spotify', as: :user_spotify_omniauth_authorize


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/comment.rb
# frozen_string_literal: true
class Comment < ApplicationRecord
  before_create :check_currently_playing
  after_create_commit :append_new_comment
  scope :by_episode_in_order_by_timestamp, ->(episode) { where(episode: episode).order(timestamp: :asc) }
  belongs_to :user
  has_many :replies

  def human_readable_timestamp
    seconds = self.timestamp / 1000
    hours = seconds / 3600
    minutes = (seconds % 3600) / 60
    remaining_seconds = seconds % 60

    sprintf('%02d:%02d:%02d', hours, minutes, remaining_seconds)
  end

  def replies_list_id
    "comment-#{id}-replies"
  end

  def list_id
    "#{episode}-comment-#{id}"
  end

  private

  def check_currently_playing
    # Fetch currently playing episode and timestamp if the user has an access token
  episode_and_timestamp = user.get_currently_playing_episode_and_timestamp if user.access_token.present?

  # Update timestamp if the episode ID matches the currently playing episode
  if episode_and_timestamp.present? && episode_and_timestamp[:id] == episode
    self.timestamp = episode_and_timestamp[:timestamp]
  end
  end

  def find_closest_comment_dom_id
    Comment
      .where.not(id: id)
      .where("timestamp <= ? AND episode = ?", timestamp, episode)
      .order(timestamp: :desc, created_at: :desc)
      .first&.list_id
  end

  def append_new_comment
    broadcast_append_to(
      self.episode,
      target: determine_target_value,
      html: ApplicationController.render(
        CommentComponent.new(comment: self),
        layout: false
      )
    )
  end

  def determine_target_value
    # if there is no closest comment the target value is the comment list
    find_closest_comment_dom_id || "comment-list"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
    current_user.comments.create(comment_params)

    respond_to do |format|
      format.html { redirect_to episode(episode: current_episode) }
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          "comment-form",
          partial: '/comments/form',
          locals: {comment: Comment.new,
          episode: current_episode,
          }
        )
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:episode, :timestamp, :content)
  end

  def current_episode
    params[:comment][:episode]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div id= "comment-form" class="mt-6 flex gap-x-3">
  <img src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="h-6 w-6 flex-none rounded-full bg-gray-50">
  <%= form_with model: comment, id: "new_comment_form", url: comments_create_path, method: :post, data: {turbo_frame: "episode"}, class: "relative flex-auto" do |form| %>
    <div class="overflow-hidden rounded-lg pb-12 shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600">
      <div class="flex">
        <%= form.label :comment, "Add your comment", class: "block ml-3 mt-2 text-sm font-medium leading-6 text-gray-900" %>
        <%= form.label :comment,  value: '00:00:00', 'data-spotify-target': 'timestampLabel', class: "block ml-3 mt-2 text-sm font-medium leading-6 text-gray-900" %>
        <%= form.hidden_field :timestamp, value: 0, 'data-spotify-target': 'timestamp' %>
      </div>
      <%= form.hidden_field :episode, value: episode %>
      <%= form.text_area :content, rows: 4, data: { spotify_target: 'textArea'  }, class: "block w-full resize-none border-0 bg-transparent py-1.5 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6", placeholder: "Add your comment..." %>
    </div>
    <%= form.submit 'Post', class: "px-4 py-3 ml-3 font-medium bg-gray-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-gray-400 focus:ring-4 ring-0 focus:ring-gray-100" %>
  <% end %>
</div>

app/views/comments/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#index</h1>
  <p>Find me in app/views/comments/index.html.erb</p>
</div>