config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  # get '/spotify_auth', to: 'application#spotify_auth'

  get 'comments/index'
  post 'comments/create'
  get 'comments/:comment_id/replies', to: 'replies#index', as: :comments_replies_index
  get 'comments/:comment_id/replies/hide', to: 'replies#hide', as: :comments_replies_hide
  post 'comments/:comment_id/replies', to: 'replies#create', as: :comments_replies_create

  get 'episodes/:id', to: 'episodes#show', as: :episode
  get 'episodes/index'
  get 'episodes/search'

  get 'podcasts/index'
  get 'podcasts/show/:id', to: 'podcasts#show', as: :podcasts_show
  get 'podcasts/search'

  # get '/users/spotify/omniauth_authorize', to: 'users/omniauth_callbacks#spotify', as: :user_spotify_omniauth_authorize
  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions',
  # registrations: 'users/registrations'}
  # config/routes.rb
devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

# Custom route for Spotify OmniAuth authorization
# get '/users/spotify/omniauth_authorize', to: 'users/omniauth_callbacks#spotify', as: :user_spotify_omniauth_authorize


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/podcast.rb
class Podcast < ApplicationRecord
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :authenticate_user!
  before_action :add_search_to_breadcrumb

  def index
  end

  def show
    @podcast = SpotifyApi.find_show(params[:id])
    add_breadcrumb @podcast.name, podcasts_show_url(@podcast.id)
    @pagy, @episodes = pagy_custom_episode(@podcast)
  end

  def search
    @query = params[:query] || ""
    @pagy, @podcasts = pagy_custom_show(params[:query]) if params[:query].present?
  end

  private

  def pagy_custom_show(query)
    pagy = Pagy.new(count: SpotifyApi.search_shows(query).total, page: params[:page])
    [pagy, SpotifyApi.search_shows(query, pagy.offset, pagy.items)]
  end

  def pagy_custom_episode(podcast)
    pagy = Pagy.new(count:SpotifyApi.show_total_episodes(podcast.id), page: params[:page])
    [pagy, podcast.episodes(offset: pagy.offset, limit: pagy.items, market: "US")]
  end

end

app/helpers/podcasts_helper.rb
module PodcastsHelper
  include Pagy::Frontend
end

app/views/podcasts/search.html.erb
<div class="p-10">
  <h1 class="font-bold text-4xl">Podcasts search</h1>
  <%= form_with(url: podcasts_search_path, method: :get, data: {turbo_frame: "podcasts"}) do |form| %>

  <%= form.label :query, "Search Podcast:", class: "block mb-2" %>
    <div class="flex space-x-3">
      <%= form.text_field :query, value: @query, class: "py-3 px-4 rounded border ring-0 focus:ring-4 focus:ring-grey-500 focus:shadow-none focus:border-gray-1000 focus:outline-none" %>

      <%= form.submit 'Search', class: "px-4 py-3 font-medium rounded-md bg-indigo-600  font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
    </div>
  <% end %>

  <% if @pagy.present? %>
    <div class="mt-4">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>

  <ul role="list" class="divide-y divide-gray-100">
    <%= render PodcastComponent.with_collection(@podcasts) %>
  </ul>

  <% if @pagy.present? %>
    <div class="mt-4">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/podcasts/show.html.erb
<div class="m-4 px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <img class="h-28 w-28 mt-2" src=<%= @podcast.images.second["url"] %> alt="">
      <h1 class="text-base font-semibold leading-6 text-gray-900"><%= @podcast.name %></h1>
      <p class="mt-2 text-sm text-gray-700"><%= @podcast.description %></p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <button type="button" class="block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Follow</button>
    </div>
  </div>


  <div class="mt-8 flow-root">
        <% if @pagy.present? %>
          <div class="m-4 mr-4">
            <%== pagy_nav(@pagy) %>
          </div>
        <% end %>
        
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Title</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Description</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Release Date</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
        
          <tbody class="divide-y divide-gray-200">

            <% @episodes.each do |episode| %>
              <tr>
                <td class="whitespace-wrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= episode.name %></td>
                <td class="whitespace-wrap px-3 py-4 text-sm text-gray-500"><%= episode.description %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= episode.release_date %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <%= link_to 'Chat', {controller: "episodes", action: "show", id: episode.id}, data: { turbo: false }, class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>

          </tbody>
        </table>

        <% if @pagy.present? %>
          <div class="mt-4">
            <%== pagy_nav(@pagy) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>